@echo off
chcp 65001 >nul
cls
echo.
echo ================================================
echo          前端生产环境配置更新工具
echo ================================================
echo.
echo 请先从 Render 获取你的后端 URL
echo 格式：https://portfolio-backend-xxxx.onrender.com
echo.
echo ================================================
echo.

set /p BACKEND_URL="请输入你的 Render 后端 URL: "

:: 验证 URL 格式
echo %BACKEND_URL% | findstr /C:"onrender.com" >nul
if errorlevel 1 (
    echo.
    echo [警告] URL 格式可能不正确
    echo 应该类似：https://portfolio-backend-xxxx.onrender.com
    echo.
    set /p CONTINUE="是否继续？(Y/N): "
    if /i not "!CONTINUE!"=="Y" exit /b 1
)

:: 创建 .env.production 文件
echo # Production environment variables > portfolio\.env.production
echo # Auto-generated by configure-production.bat >> portfolio\.env.production
echo. >> portfolio\.env.production
echo # Backend API URL >> portfolio\.env.production
echo VITE_API_URL=%BACKEND_URL%/api >> portfolio\.env.production
echo. >> portfolio\.env.production
echo # WebSocket URL for real-time sync >> portfolio\.env.production
echo VITE_WS_URL=%BACKEND_URL%/ws >> portfolio\.env.production

echo.
echo ================================================
echo   ✓ 配置已更新！
echo ================================================
echo.
echo 文件内容：
type portfolio\.env.production
echo.
echo ================================================
echo.
echo 下一步操作：
echo.
echo 1. 提交配置到 Git:
echo    git add portfolio\.env.production
echo    git commit -m "update: 配置生产环境 API 和 WebSocket URL"
echo    git push
echo.
echo 2. 部署前端到 Netlify
echo.
echo ================================================
echo.

set /p COMMIT=是否现在提交到 Git? (Y/N): 
if /i "%COMMIT%"=="Y" (
    git add portfolio\.env.production
    git commit -m "update: 配置生产环境 API 和 WebSocket URL"
    git push
    
    if !errorlevel! equ 0 (
        echo.
        echo ✓ 配置已提交到 GitHub！
        echo.
        echo 现在可以部署前端到 Netlify：
        echo   1. 访问 https://netlify.com
        echo   2. 登录 GitHub 账号
        echo   3. Add new site ^> Import project
        echo   4. 选择 portfolio-website 仓库
        echo   5. 点击 Deploy site
    ) else (
        echo.
        echo ✗ 提交失败，请手动执行
    )
) else (
    echo.
    echo 请手动执行提交操作
)

echo.
pause
